# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish ./TimeStamper/TimeStamper.csproj -c Release -o ChocolateyPackage/timestamper/Tools
    - name: Chocolatey Pack 
      run: choco pack ./ChocolateyPackage/timestamper/timestamper.nuspec
    - name: Chocolatey Push
      run: choco push timestamper.0.0.1.nupkg --source https://push.chocolatey.org/ --key ${{ secrets.PUSH_REPO_KEY }}
