# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  release:
    types: [created]
  pull_request:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build with .Net Framework
      run: ./actions/build.ps1 --target=CI
    - name: Upload Windows build results
      uses: actions/upload-artifact@v3
      # Always upload build results
      if: ${{ always() }}
      with:
        name: windows-build-results
        path: |
          code_drop\TestResults\issues-report.html
          code_drop\TestResults\NUnit\TestResult.xml
          code_drop\TestCoverage\lcov.info
          code_drop\TestCoverage\OpenCover.xml
          code_drop\Packages\**\*.nupkg
          code_drop\MsBuild.log
